theme: jekyll-theme-slate
title: Det Digitale Folkebibliotek - Manual for Folkebibliotekernes CMS
description: Manualen har til formål at hjælpe med administration, opsætning og redaktionelle opgaver for Folkebibliotekernes CMS.
